import "../styles/globals.css";
import styles from "../styles/Home.module.css";
import type { AppProps } from "next/app";
import { Provider } from "react-redux";
import { store } from "../store/store";
import Head from "next/head";
import Header from "../components/Header/Header";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Head>
        <title>ResumeFromSpace - free resume creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <div className={styles.container}>
        <main className="container flex flex-col mx-auto p-4 min-h-screen overflow-hidden">
          <Header />
          <div className="flex flex-col md:flex-row gap-8 flex-1 mt-16">
            <Component {...pageProps} />
          </div>
        </main>
      </div>
    </Provider>
  );
}
export default MyApp;
